export const setupTranslations = {
    ID: {
      selectLang: "Pilih Bahasa",
      chooseLang: "Pilih bahasa preferensi Anda",
      createDb: "Buat Database",
      needSheet: "Anda memerlukan Google Sheet sendiri untuk menyimpan data.",
      officialTempl: "Template Resmi",
      weHavePrep: "Kami telah menyediakan master sheet lengkap dengan kolom dan script yang dibutuhkan. Klik di bawah untuk menyalin ke Google Drive Anda.",
      copyTempl: "Salin Template Database",
      afterCopy: "Setelah menyalin, biarkan tab terbuka! Anda perlu men-deploy script di langkah berikutnya.",
      connectApi: "Hubungkan API",
      deployScript: "Deploy script dan tempel URL di sini.",
      howTo: "Cara mendapatkan URL?",
      step1: "1. Di Google Sheet, buka **Extensions > Apps Script**.",
      step2: "2. Klik tombol biru **Deploy** (kanan atas) > **New Deployment**.",
      step3: "3. Pilih tipe: **Web App** (ikon gerigi).",
      step4: "4. Set **Who has access** ke: **Anyone** (Siapa saja).",
      step5: "5. Klik **Deploy** dan salin **Web App URL**.",
      labelUrl: "URL Web App Apps Script",
      placeholderUrl: "https://script.google.com/macros/s/...",
      urlHint: "Pastikan URL berakhiran /exec",
      testConn: "Tes Koneksi",
      testing: "Menguji...",
      allSet: "Selesai!",
      dashConnected: "Dashboard Anda kini terhubung ke database pribadi.",
      defCreds: "Akun Default",
      email: "Email",
      pass: "Password",
      changeLater: "Anda bisa mengubah ini di sheet 'Profile' nanti.",
      btnLogin: "Masuk ke Login",
      btnNext: "Lanjut",
      btnBack: "Kembali",
      btnFinish: "Selesai",
      btnSave: "Menyimpan...",
      errUrl: "Format URL salah. Harus berakhiran /exec",
      errConn: "Gagal terhubung. Cek URL atau Deployment.",
      successConn: "Koneksi Berhasil!",
      enterValid: "Masukkan URL yang valid",
      copyEmail: "Email disalin!",
      copyPass: "Password disalin!",
      googleWarnTitle: "Peringatan Keamanan Google",
      googleWarnText: "Jika muncul peringatan 'Google hasn't verified this app' atau 'Back to safety' saat otorisasi, klik **Advanced** -> **Go to ... (unsafe)**. Ini aman karena script ini adalah milik Anda sendiri.",
      desktopRecTitle: "Rekomendasi Perangkat",
      desktopRecText: "Untuk pengalaman setup terbaik dan menghindari kesalahan copy-paste, kami sangat menyarankan menggunakan **Laptop atau PC Desktop**.",
      mustTest: "Koneksi harus berhasil untuk melanjutkan."
    },
    EN: {
      selectLang: "Select Language",
      chooseLang: "Choose your preferred language",
      createDb: "Create Your Database",
      needSheet: "You need your own Google Sheet to store data.",
      officialTempl: "Official Template",
      weHavePrep: "We have prepared a master sheet with all necessary columns and scripts. Click below to make a copy to your Google Drive.",
      copyTempl: "Copy Database Template",
      afterCopy: "After copying, keep the tab open! You will need to deploy the script in the next step.",
      connectApi: "Connect API",
      deployScript: "Deploy the script and paste the URL here.",
      howTo: "How to get the URL?",
      step1: "1. In your Google Sheet, go to **Extensions > Apps Script**.",
      step2: "2. Click the blue **Deploy** button (top right) > **New Deployment**.",
      step3: "3. Select type: **Web App** (gear icon).",
      step4: "4. Set **Who has access** to: **Anyone**.",
      step5: "5. Click **Deploy** and copy the **Web App URL**.",
      labelUrl: "Apps Script Web App URL",
      placeholderUrl: "https://script.google.com/macros/s/...",
      urlHint: "Make sure the URL ends with /exec",
      testConn: "Test Connection",
      testing: "Testing...",
      allSet: "All Set!",
      dashConnected: "Your dashboard is now connected to your private database.",
      defCreds: "Default Credentials",
      email: "Email",
      pass: "Password",
      changeLater: "You can change these in the 'Profile' sheet later.",
      btnLogin: "Go to Login",
      btnNext: "Next",
      btnBack: "Back",
      btnFinish: "Finish Setup",
      btnSave: "Saving...",
      errUrl: "Invalid URL format. Must end with /exec",
      errConn: "Connection failed. Check URL or Deployment.",
      successConn: "Connection Successful!",
      enterValid: "Please enter a valid URL",
      copyEmail: "Email copied!",
      copyPass: "Password copied!",
      googleWarnTitle: "Google Security Warning",
      googleWarnText: "If you see 'Google hasn't verified this app' or 'Back to safety' during authorization, click **Advanced** -> **Go to ... (unsafe)**. This is safe as the script belongs to you.",
      desktopRecTitle: "Device Recommendation",
      desktopRecText: "For the best setup experience and to avoid copy-paste errors, we highly recommend using a **Laptop or Desktop PC**.",
      mustTest: "Connection must be successful to proceed." 
    }
  };
